version: '2'
services:
    proyectoregistroacademico-app:
        image: proyectoregistroacademico
        external_links:
            - proyectoregistroacademico-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/proyectoregistroacademico?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    proyectoregistroacademico-mysql:
        extends:
            file: mysql.yml
            service: proyectoregistroacademico-mysql
