version: '2'
services:
    proyectoregistroacademico-sonar:
        container_name: proyectoregistroacademico-sonar
        image: sonarqube:5.6.1-alpine
        ports:
            - 9000:9000
            - 9092:9092
